// ================= CONSTANTES =================
#define DIALOG_LOGIN        1
#define DIALOG_REGISTER     2
#define DIALOG_MENU         10
#define DIALOG_PREFEITURA   20
#define DIALOG_EMPREGOS     21
#define DIALOG_GPS          30

#define EMPREGO_NENHUM      0
#define EMPREGO_POLICIA     1
#define EMPREGO_SAMU        2
#define EMPREGO_TAXI        3
#define EMPREGO_MEC         4

#define SPAWN_X 1702.5
#define SPAWN_Y 328.5
#define SPAWN_Z 10.0
#define SPAWN_SKIN 26
