#if defined _cfg_constants_included
    #endinput
#endif
#define _cfg_constants_included

// ================= DIALOGS =================
#define DIALOG_LOGIN        1
#define DIALOG_REGISTER     2
#define DIALOG_MENU_PRINCIPAL  100
#define DIALOG_PREFEITURA      110
#define DIALOG_EMPREGOS        111
#define DIALOG_GPS             120
#define DIALOG_AJUDA           130

// ================= EMPREGOS =================
#define EMPREGO_NENHUM   0
#define EMPREGO_POLICIA  1
#define EMPREGO_SAMU     2
#define EMPREGO_TAXI     3
#define EMPREGO_MEC      4

// ================= SPAWN =================
#define SPAWN_X 1702.5
#define SPAWN_Y 328.5
#define SPAWN_Z 10.0
#define SPAWN_SKIN 26
